### ISSUE TITLE
Problem running dev server using yarn

### ISSUE THREAD

**Issue by rkaranam** [coderplex/coderplex#100] opened 2017-11-09 19:35 UTC
![image](https://user-images.githubusercontent.com/13974570/32625588-a0353f5c-c5b2-11e7-9ba9-60071d105857.png)

I am getting this issue when trying to run dev server.. Need help!

**Comment by vinaypuppal** [comment] 2017-11-09 19:39
Hi, @rkaranam 

Which Node version do you have?
This project needs node version 8 or above as mentioned in our contribution guide requirements](https://github.com/coderplex/coderplex/blob/master/CONTRIBUTING.md#running-this-project-locally)

**Comment by rkaranam** [comment] 2017-11-09 20:14
@vinaypuppal v6.7.0. I tried updating node using [npm-windows-upgrade](https://www.npmjs.com/package/npm-windows-upgrade) but it is of no use. It would be really helpful if you can provide the link for easiest updation of node on Windows.

**Comment by vinaypuppal** [comment] 2017-11-09 20:22
@rkaranam Sorry I dont use windows O.S so no idea how to upgrade node on windows. I think @M-ZubairAhmed can help you with this.

**Comment by vinaypuppal** [comment] 2017-11-09 20:32
Try this https://github.com/coreybutler/nvm-windows

**Comment by rkaranam** [comment] 2017-11-10 18:11
@vinaypuppal Thanks Vinay, it helped in installing node 8.9.1. Allthough I ran into a couple of [issues](https://github.com/coreybutler/nvm-windows/issues/289), finally I am able to run the dev server and can see the application at port 3000. BTW, Yarn is awesome!

**Comment by vinaypuppal** [comment] 2017-11-10 20:16
oh that's good to hear. Since the problem is solved I am closing this and #101 issues. 
We will be adding this upgrade info and other required details soon to contribution guide with #102 .

**Closed by vinaypuppal** 2017-11-10 20:16 UTC
